Implement IntakeSubsystem and IntakeCommand
momentumfrc/2020InfiniteRecharge pull request #7
Opened 2020-02-21 02:55 UTC by FireShredder24

Implements a Subsystem that controls the 2 AM-RedLine motors that spin the intake rollers and a Command that binds said Subsystem to the controller.

2020-02-24 19:21 UTC, terbos90803 requested changes

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/Constants.java
> +  public static final int INTAKE_PISTON_PCM_CHAN_LF_F = 1;
Consider renaming with higher level sense of direction.
Instead of F and R for forward and reverse, perhaps choose DEPLOY and STOW.

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/commands/IntakeCommand.java
> +  @SuppressWarnings({ "PMD.UnusedPrivateField", "PMD.SingularField" })
Don't suppress warnings at this time.  You need to be reminded that the code is not complete.

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/commands/IntakeCommand.java
> +  private RobotContainer m_container;
Should be final.

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/commands/IntakeCommand.java
> +   * Creates a new ExampleCommand.
Update comment

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/commands/IntakeCommand.java
> +    if (m_container.mainController.getIntakePowerCells()) {
I know that the example code from last year did this kind of things where a command would keep running and then poll the joystick buttons.  While this does work, the intended usage of the Button commands is to trigger on a button press, update the subsystem state, and then end.
We should talk about this.

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/commands/IntakeCommand.java
> +  private boolean isLowered = false;
You should not hold state in the Command.  State should be held in the subsystem.

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/controllers/DriveController.java
> +  abstract public boolean getToggleIntake();
The abstract keyword is not needed for interfaces as it's implied.

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    intakeSPrt.set(0.3);
1) No magic numbers.  Use named constants.
2) Should move motor set calls into periodic method.
3) Better API is: public void runIntake(bool run);

2020-02-24 19:21 UTC, terbos90803 commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    intakePistonL.set(DoubleSolenoid.Value.kForward);
Should replace reference to kForward etc with class constants to abstract Deploy vs Stow.

2020-02-24 20:06 UTC, lost1227 commented on src/main/java/frc/robot/commands/IntakeCommand.java
> +  @SuppressWarnings({ "PMD.UnusedPrivateField", "PMD.SingularField" })
We don't even use the PMD analyzer. I'm guessing this is left over from an example somewhere (I'm pretty sure wpilib uses PMD).

2020-02-25 01:57 UTC, FireShredder24 commented on src/main/java/frc/robot/commands/IntakeCommand.java
> +  @SuppressWarnings({ "PMD.UnusedPrivateField", "PMD.SingularField" })
Yeah, that was from the ExampleCommand.

2020-02-26 19:24 UTC, terbos90803 requested changes

2020-02-26 19:24 UTC, terbos90803 commented on src/main/java/frc/robot/Constants.java
> +  public static final int INTAKE_PISTON_PCM_CHAN_RT_STOW = 4;
PCM channels are numbered 0-7.

2020-02-26 19:24 UTC, terbos90803 commented on src/main/java/frc/robot/commands/intake/IntakePistonToggle.java
> +public class IntakePistonToggle extends CommandBase {
Blanket comment to all Commands:  The name of the class should have Command or at least Cmd in it.  This promotes readability of the calling code.  Whichever you choose, be consistent across all instances.

2020-02-26 19:24 UTC, terbos90803 commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    if (runIntake && !reverseIntake) {
Calculate motor setpoint first, then always set the motor value, even if it's zero.
If you don't set the motor, you get a bunch of watchdog warnings.

2020-02-27 17:51 UTC, terbos90803 requested changes

2020-02-27 17:51 UTC, terbos90803 commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  private final double rollerSetpoint = 0.3;
Should be a MoPref so we can tune it from the ShuffleBoard.

2020-02-27 17:51 UTC, terbos90803 commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +      intakeSPrt.set(0);
Good coding practice is to only set the motor values in one place.  Do all the math/selection first, then set the values once.

Example:
```
double setpoint = runIntake ? rollerSetpoint : 0;
if (reverseIntake)
  setpoint = -setpoint;

intakeSPlf.set(setpoint);
intakeSPrt.set(setpoint);
```

2020-03-01 23:05 UTC, terbos90803 requested changes

2020-03-01 23:05 UTC, terbos90803 commented on src/main/java/frc/robot/RobotContainer.java
> +  private final JoystickButton intakePistonToggle = new JoystickButton(f310, 2/* B */);
There should be enums for the named buttons instead of numbers.

2020-03-01 23:05 UTC, terbos90803 commented on src/main/java/frc/robot/commands/intake/IntakePistonCmd.java
> +/*----------------------------------------------------------------------------*/
Each of these command files is 99% boilerplate and 1 line of useful code.  These should all be converted to lambdas in configureButtonBindings.

2020-03-01 23:05 UTC, terbos90803 commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  private final VictorSP intakeSPrt = new VictorSP(Constants.INTAKE_VICTORSP_PWM_CHAN_LF);
Robot System says there is only one PWM mapped for both motors, so only need one Victor class.

2020-03-02 00:14 UTC, terbos90803 approved these changes
Ok.  I think that's close enough to go.

2020-03-02 00:17 UTC, merged